### ISSUE TITLE
Crash with particle rain 2.1.5

### ISSUE THREAD

**Issue by SettingDust** [AViewFromTheTop/ParticleTweaks#1]
https://modrinth.com/mod/particle-rain/version/2.1.5-backport

**Comment by AViewFromTheTop** [comment]
I’m not supporting this mod on 1.20 versions anymore, so I’m sorry. 1.21+ is being supported.

**Comment by NikkMann** [comment]
Darn, would've loved to have the new 2.0 features on 1.20.1
