### ISSUE TITLE
Version 2.0 won't work with Minecraft 1.21

### ISSUE THREAD

**Issue by Coder-Relri** [AViewFromTheTop/ParticleTweaks#2]
Since version 2.0 uses Fabric API 1.03 and above, the mod can't work with 1.21. Just mentioning since on modrinth it's said that the mod can be used with 1.21 - 1.21.1.

**Comment by AViewFromTheTop** [comment]
Bruh how did I screw up
Will fix later today

**Comment by AViewFromTheTop** [comment]
Fixed!
Just redownload 2.0 from Modrinth.
