### ISSUE TITLE
Particles dont fade in 1.21.4 when using either Particle Interactions or Iris

### ISSUE THREAD

**Issue by slushieuwu** [AViewFromTheTop/ParticleTweaks#4]
They all worked fine together on 1.21.3
https://modrinth.com/mod/particle-interactions
https://modrinth.com/mod/iris

**Comment by AViewFromTheTop** [comment]
I've not changed anything that would impact this on the 1.21.4 branch. Please use the latest version. If it still occurs, report it to them.
